version = 1

[[annotations]]
path = [
    "README.md",
    "REUSE.toml",
    "tests.zig",
    "build.zig",
    "build.zig.zon",
    ".nvchecker.toml",
    ".gitignore",
    ".gitattributes",
    ".github/**/*.yml",
]
SPDX-FileCopyrightText = "Zig Devel contributors"
SPDX-License-Identifier = "0BSD OR Zlib"
